name: Build Debian Package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Install build dependencies
        run: |
          sudo apt-get update
          # Install essential Debian packaging tools
          sudo apt-get install -y \
            build-essential devscripts debhelper fakeroot lintian
          sudo apt-get build-dep -y .

      - name: Build Debian package
        run: |
          dpkg-buildpackage -us -uc -b

      - name: Show results
        run: |
          ls -lh ..
          echo "Generated DEB files:"
          ls -lh ../*.deb
          mv ../*.deb ./

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: ./*.deb
